### ISSUE TITLE
pip for python2 is used on a python3 project

### ISSUE THREAD

**Issue by skytreader** [serverless/serverless-python-requirements#440] opened 2019-12-13 09:55 UTC
Following off from #439 (I edited some node_module files to just give me a sensible stack trace).

Though I have the following declaration on my `serverless.yml`:

```
provider:
  name: aws
  runtime: python3.6
```

Running `serverless deploy` gives me the following:

```
Serverless: Packaging required Python packages...

/serverless_project/node_modules/serverless/lib/classes/Error.js:94
    throw new Error(e);
          ^
Error: Traceback (most recent call last):
  File "/serverless_project/.requirements/.venv/bin/pip", line 6, in <module>
    from pip._internal.main import main
ModuleNotFoundError: No module named 'pip._internal.main'
Failed to install requirements from: /serverless_project/node_modules/serverless-wsgi/requirements.txt

    at process.module.exports.logError.e (/serverless_project/node_modules/serverless/lib/classes/Error.js:94:11)
    at process.emit (events.js:198:13)
    at process.emit (/serverless_project/node_modules/source-map-support/source-map-support.js:465:21)
    at /serverless_project/node_modules/bluebird/js/release/debuggability.js:199:33
    at activeFireEvent (/serverless_project/node_modules/bluebird/js/release/debuggability.js:242:44)
    at fireRejectionEvent (/serverless_project/node_modules/bluebird/js/release/debuggability.js:632:14)
    at Promise._notifyUnhandledRejection (/serverless_project/node_modules/bluebird/js/release/debuggability.js:65:9)
    at Timeout._onTimeout (/serverless_project/node_modules/bluebird/js/release/debuggability.js:44:14)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

This happens even after I delete the `.requirements` directory and rerun `serverless deploy`. It seems that it keeps using the wrong pip for my python version. How do I fix this?

**Comment by miketheman** [comment] 2020-02-19 04:55
@skytreader Circling back to this - were you ever able to overcome this issue? I'm trying to understand what I might need in place today to reproduce this kind of error.

**Comment by pgrzesik** [comment] 2022-10-21 22:34
Hey 👋 I'm closing this ticket as it looks like it's heavily outdated, we can of course reopen it if needed 👍

**Closed by pgrzesik** 2022-10-21 22:34 UTC
Labels: bug
